export enum ListName {
    USER_LIST = 'USER_LIST',
    TENANCY_LIST = 'TENANCY_LIST',
    DEVICE_LIST = 'DEVICE_LIST',
    TENANCY_DEVICE_LIST = 'TENANCY_DEVICE_LIST',
    TENANCY_USER_LIST = 'TENANCY_USER_LIST'
}